export const ADD_EXERCISE = 'ADD_EXERCISE';
export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
export const COMPLETE_EXERCISE = 'COMPLETE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const SELECT_DAY = 'SELECT_DAY';