const ADD_EXERCISE = 'ADD_EXERCISE';
const REMOVE_EXERCISE = 'REMOVE_EXERCISE';
const COMPLETE_EXERCISE = 'COMPLETE_EXERCISE';
const UPDATE_EXERCISE = 'UPDATE_EXERCISE';

export {
  ADD_EXERCISE,
  REMOVE_EXERCISE,
  COMPLETE_EXERCISE,
  UPDATE_EXERCISE,
};
